### ISSUE TITLE
Add visualization through graphs to plot loss/epoch live while training.

### ISSUE THREAD

**Issue by TarunTomar122** [RoboticsClubIITJ/ML-DL-implementation#10]
Right we don't have any way to see how our loss per epoch is working or how our parameters are affecting the loss of our algorithm. We need some visualisation through graphs which can be done using matplotlib and cv2. Make some functions that can do the same.

**Comment by PawanSuryavanshi95** [comment]
I made another class to visualize data, modified fit function to return costs, made a PR.

**Comment by TarunTomar122** [comment]
@rohansingh9001  have a look!
