### ISSUE TITLE
EXTEND THE MODEL OF  LINEAR REGRESSION INTO MULTI VARIABLE DATA

### ISSUE THREAD

**Issue by RATED-R-SUNDRAM** [RoboticsClubIITJ/ML-DL-implementation#109]
THE CODE IN THE LINEAR REGRESSION HAS THE INPUT VARIABLE X AS 1D ARRAY SIGNIFYING A ONE FEATURED INPUT BUT WE CAN ALSO EXTEND THE CONCEPT OF LINEAR REGRESSION TO A MULTIPLE VARIABLE DATA

**Comment by kwanit1142** [comment]
Closing the Issue, as the implementation is not only to linear regression, but it will be applicable to other models too. In addition to this, the above-mentioned issue will be taken care of, when the library will have a sufficiently larger number of models.
