### ISSUE TITLE
Change All Functions and Matrices to accepted standards in the DL community.

### ISSUE THREAD

**Issue by TarunTomar122** [RoboticsClubIITJ/ML-DL-implementation#11]

**Comment by uakarsh** [comment]
Can you explain the issue specifically? I mean to ask, that what do you want to modify specifically?

**Comment by TarunTomar122** [comment]
Leave this issue for now... Work on other issues cause this issue is supposed to fix the code structure and some function and terminologies to work up with actually DL standards.

**Comment by rohansingh9001** [comment]
@uakarsh Right now, some functions in some places do not follow proper nomenclature or matrix dimensions as discussed and accepted by research papers worldwide.

We wish to change the matrix and tensor sizes and dimensions to those standards.

**Comment by kwanit1142** [comment]
Can I work on this?
