### ISSUE TITLE
Implement Lasso regression a.k.a L1 Regularization

### ISSUE THREAD

**Issue by kwanit1142** [RoboticsClubIITJ/ML-DL-implementation#132]
Resources:-

https://www.geeksforgeeks.org/implementation-of-lasso-regression-from-scratch-using-python/    <------(Apart from sklearn import due to train-test split, Implementation is relevant enough to be referred)

https://mlforanalytics.com/2018/05/29/lasso-regression-and-its-implementation-with-python/

https://machinelearningmastery.com/lasso-regression-with-python/ <-----------------(Just for Application purposes, to be referred in later stages)

**Comment by harsh-ux** [comment]
I would like to work on it

**Comment by kwanit1142** [comment]
Issue's completed, so dissolving it now.
