### ISSUE TITLE
Create a proper Readme File for this module. Explain the functions implemented and the code structure properly.

### ISSUE THREAD

**Issue by TarunTomar122** [RoboticsClubIITJ/ML-DL-implementation#16]

**Comment by kwanit1142** [comment]
can this issue be clarified in more precise way, like are we talking about loss functions or prediction function?

**Comment by TarunTomar122** [comment]
@kwanit1142  yes we need a complete official readme for our repo. This must include but not limited to the algorithms that we are working on, algorithms we have finished, some resources, our aim, how to contribute and what all librarires we are using....

**Comment by kwanit1142** [comment]
ohk, so in that case, I can contribute

**Comment by rohansingh9001** [comment]
@kwanit1142 You can start writing content for the repo and how to contribute. We will share this issue together.

**Comment by kwanit1142** [comment]
ohk, so in a better planned way, @rohansingh9001 which part you are working on and which portion I have to write?

**Comment by slowdivesun** [comment]
can i help in this?

**Comment by TarunTomar122** [comment]
Thanks for contribution... Closing NOw
