### ISSUE TITLE
Implement KNN Classifier

### ISSUE THREAD

**Issue by kwanit1142** [RoboticsClubIITJ/ML-DL-implementation#174]
References :-

https://machinelearningmastery.com/tutorial-to-implement-k-nearest-neighbors-in-python-from-scratch/
https://towardsdatascience.com/how-to-build-knn-from-scratch-in-python-5e22b8920bd2

**Comment by alivejojo** [comment]
I would like to work on this, thanks.

**Comment by kwanit1142** [comment]
Sure, understand the problem and make your implementation accordingly, with the limitation of using only numpy and matplotlib.
