### ISSUE TITLE
Move all examples into an examples directory for more managed file structure.

### ISSUE THREAD

**Issue by rohansingh9001** [RoboticsClubIITJ/ML-DL-implementation#18]
Currently, all the examples are placed in the root directory of the repository. For now, there are only 2 examples. However, later this may become an issue and clutter up the root directory. We wish to move these examples into a root/examples directory for better file management.

**Comment by hiteshidudeja** [comment]
I would like to work on that

**Comment by rohansingh9001** [comment]
@hiteshidudeja assigned.

**Comment by rohansingh9001** [comment]
@hiteshidudeja If you are facing any issues you can ask here in comments.

**Comment by hiteshidudeja** [comment]
@rohansingh9001 I am facing difficulty in importing MLlib module after creating examples-directory.

**Comment by rohansingh9001** [comment]
@hiteshidudeja You can have a look into [absolute imports](https://www.geeksforgeeks.org/absolute-and-relative-imports-in-python/) in python. Hope that will solve your problem.

**Comment by agrawalshubham01** [comment]
@rohansingh9001 @hiteshidudeja I think, the better way for this would be to add examples in documentation of each functions. So the end user could understand as well as use the code base.

**Comment by rohansingh9001** [comment]
We can add examples in both the repo and the docs which are being made.

**Comment by TarunTomar122** [comment]
Closing this as we have got a PR already!
