### ISSUE TITLE
Implementing Absolute Error loss function

### ISSUE THREAD

**Issue by Saptashrungi** [RoboticsClubIITJ/ML-DL-implementation#20]
Resources for the same:

https://towardsdatascience.com/importance-of-loss-function-in-machine-learning-eddaaec69519
https://towardsdatascience.com/understanding-the-3-most-common-loss-functions-for-machine-learning-regression-23e0ef3e14d3

**Comment by RidhimaKohli** [comment]
I would like to work on this.

**Comment by rohansingh9001** [comment]
@RidhimaKohli Go ahead issue assigned to you

**Comment by agrawalshubham01** [comment]
Fixed in PR #32 .
