### ISSUE TITLE
Adding more Activation Functions

### ISSUE THREAD

**Issue by SaiSrichandra** [RoboticsClubIITJ/ML-DL-implementation#28]
Hello,
I have checked out the code and found out, you are using only Sigmoid as your activation function
I would like to add other activations like Softmax, Relu, Leaky Relu, Tanh, etc

**Comment by SaiSrichandra** [comment]
I would like to work on this issue

**Comment by agrawalshubham01** [comment]
Sure, Go Ahead.

**Comment by rohansingh9001** [comment]
@SaiSrichandra since your PR was merged. I believe this issue has been resolved. Is there anything more that you wish to add?

Thanks for your contribution so far!
