### ISSUE TITLE
Adding Doc strings.

### ISSUE THREAD

**Issue by agrawalshubham01** [RoboticsClubIITJ/ML-DL-implementation#30]
There are many classes and function where the doc strings aren't added.

**Comment by Mayank662** [comment]
Sir @agrawalshubham01, I would like to work on this issue.

**Comment by agrawalshubham01** [comment]
Sure @Mayank662 , Go ahead.

**Comment by rohansingh9001** [comment]
@Mayank662 can you share any updates regarding this issue?

**Comment by rohansingh9001** [comment]
@Mayank662 has not forked the repository yet nor responded with any updates. This issue can be assigned to somebody else for now.

**Comment by kwanit1142** [comment]
can I work on this issue too?

**Comment by RidhimaKohli** [comment]
Can I work on this ?

**Comment by RidhimaKohli** [comment]
Can I work on this ?

**Comment by kwanit1142** [comment]
Can I work too?

**Comment by agrawalshubham01** [comment]
@kwanit1142 @RidhimaKohli go ahead I am assigning this to you both. Kindly share an example here before implementation.

**Comment by TarunTomar122** [comment]
This worked nicely Thank you to the contributors!
