### ISSUE TITLE
Implement K-Means Clustering

### ISSUE THREAD

**Issue by samarth-1729** [RoboticsClubIITJ/ML-DL-implementation#35]
Related resources one can follow:
https://towardsdatascience.com/k-means-clustering-from-scratch-6a9d19cafc25

**Comment by rohansingh9001** [comment]
@TarunTomar122 Is this a duplicate? Or does it need to be added?

**Comment by TarunTomar122** [comment]
@rohansingh9001  i think this is a duplicate nd i have already implemented this. We can close this issue

**Comment by samarth-1729** [comment]
If you think KNN and K-Means are same refer this link:
https://medium.com/@dhiraj8899/difference-between-k-nearest-neighbor-k-nn-and-k-means-clustering-d9a44859182f#:~:text=clear%20and%20simple-,Difference%20between%20K%2DNearest%20Neighbor(K%2D,NN)%20and%20K%2DMeans%20Clustering&text=K%2DNN%20is%20a%20Supervised,a%20clustering%20machine%20learning%20algorithm.

**Comment by TarunTomar122** [comment]
@samarth-1729  okay samarth Sir! I am sorry for misunderstanding. I apologize for any mistake and this issue is up and runnin for everyone!

**Comment by samarth-1729** [comment]
Thank you!

**Comment by kwanit1142** [comment]
@samarth-1729 , are you working in this issue too, or someone else only should work on this ?

**Comment by kwanit1142** [comment]
Can I pick this issue?

**Comment by kwanit1142** [comment]
@rohansingh9001 @TarunTomar122 @Saptashrungi @samarth-1729 , code is complete and working fine, and within 1--2 days, will push the PR for k-means-clustering
