### ISSUE TITLE
Implement Principal Component Analysis

### ISSUE THREAD

**Issue by kwanit1142** [RoboticsClubIITJ/ML-DL-implementation#52]
A Flexible Unsupervised Method to reduce the dimensionality of Input dataset, alongside preserving the information and minimizing the loss as much as possible.

Reference Literature for understanding ;

https://jakevdp.github.io/PythonDataScienceHandbook/05.09-principal-component-analysis.html

**Comment by utkarsh0702** [comment]
Can I try working on this issue.

**Comment by kwanit1142** [comment]
YES u can, but remember to only use numpy only

not any predefined libraries like scikit and all

**Comment by utkarsh0702** [comment]
Sure I will

**Comment by kritikaparmar-programmer** [comment]
Is someone working on this issue?

**Comment by utkarsh0702** [comment]
I am working on this issue.

**Comment by rohansingh9001** [comment]
@utkarsh0702 keep us updated on your progress and feel free to ask anything in the Gitter channel regarding more clarifications.

**Comment by utkarsh0702** [comment]
I have implemented main PCA functionality, trying to implement other functionalities.

**Comment by kwanit1142** [comment]
@utkarsh0702 any updates about implementation till now ?

**Comment by utkarsh0702** [comment]
I am working on the functionality, but for the past 3 days I can't as I am out of town for some reasons. I will submit the full PCA implementation on Thursday this week.

**Comment by kwanit1142** [comment]
Ok, NP..

**Comment by kwanit1142** [comment]
Closing the Issue, as it is accomplished. Thanks for contributing @utkarsh0702
