### ISSUE TITLE
Implementation of Multinomial Naive Bayes classifier

### ISSUE THREAD

**Issue by Saptashrungi** [RoboticsClubIITJ/ML-DL-implementation#57]
Resources:
https://towardsdatascience.com/multinomial-naive-bayes-classifier-for-text-analysis-python-8dd6825ece67 
https://medium.com/@johnm.kovachi/implementing-a-multinomial-naive-bayes-classifier-from-scratch-with-python-e70de6a3b92e

PS: The resources might use pandas, however implementation should be using pure python with numpy.

**Comment by bhanuexcalibur** [comment]
Can this issue be please assigned to me?
