### ISSUE TITLE
Implementation of Bernoulli Naive Bayes classifier

### ISSUE THREAD

**Issue by Saptashrungi** [RoboticsClubIITJ/ML-DL-implementation#58]
This is similar to the multinomial naive bayes but the predictors are boolean variables. The parameters that we use to predict the class variable take up only values yes or no, for example if a word occurs in the text or not.

Resources:
https://kenzotakahashi.github.io/naive-bayes-from-scratch-in-python.html

**Comment by bhanuexcalibur** [comment]
working on this, please assign this to me

**Comment by harsh-ux** [comment]
I would like to work on this @rohansingh9001. Please assign it to me.

**Comment by kwanit1142** [comment]
@harsh-ux , you are good to go from here.
