### ISSUE TITLE
Implement Polynomial regression

### ISSUE THREAD

**Issue by rohansingh9001** [RoboticsClubIITJ/ML-DL-implementation#59]
You can use the following resource for reference https://towardsdatascience.com/polynomial-regression-bbe8b9d97491.

The resource uses sklearn but we have to implement a similar API in our library. 
Implement polynomial regression in the models.py file in MLlib directory.
Also, add an example showcasing your additions in the examples folder. If you need to add a dataset for that, feel free to add it in
the datasets directory.

Also, you may inherit the LinearRegression class for your implementation just like Logistic Regression inherits it.

**Comment by ashwani-rathee** [comment]
I would like to take this up :)

**Comment by rohansingh9001** [comment]
@ashwani-rathee Go ahead.

**Comment by Halix267** [comment]
Hey @rohansingh9001  can i work on this?

**Comment by Halix267** [comment]
@agrawalshubham01 Can I take this issue as almost  a week  past and no pr is generated for this issue?

**Comment by agrawalshubham01** [comment]
@ashwani-rathee any updates??

**Comment by Halix267** [comment]
Can I take this now ??

**Comment by Halix267** [comment]
@agrawalshubham01 @rohansingh9001

**Comment by rohansingh9001** [comment]
@Halix267 Yes, it seems there are no updates from the original assignee. 

I would recommend working only on one issue for now though and you can work on the second one after you complete the first in order to reduce the load on you and leave everyone oppurtunities.

**Comment by Halix267** [comment]
ok @rohansingh9001 I will do that issue as fast as i can

**Comment by kwanit1142** [comment]
Issue closed, after its completion.
