### ISSUE TITLE
Implement Decision Trees

### ISSUE THREAD

**Issue by TarunTomar122** [RoboticsClubIITJ/ML-DL-implementation#6]
Related Resources one can Follow :-
1. https://towardsdatascience.com/decision-tree-from-scratch-in-python-46e99dfea775
2. https://machinelearningmastery.com/implement-decision-tree-algorithm-scratch-python/

**Comment by samarth-1729** [comment]
I would like to work on this issue!

**Comment by TarunTomar122** [comment]
We can't assign multiple issues to same person right away. @samarth-1729  finish one issue and then you can do more.

**Comment by samarth-1729** [comment]
Ok, No Problem!

**Comment by Saptashrungi** [comment]
I would like to work on this issue.

**Comment by TarunTomar122** [comment]
@Saptashrungi  fine. Take your time this issue is yours.

**Comment by kwanit1142** [comment]
@Shreya-IITJ, this issue is reopened, as the Implementation is not yet complete. From here on, you can continue your work.

**Comment by kwanit1142** [comment]
Thanks to @Shreya-IITJ. Now Finally Closing this Issue.
