### ISSUE TITLE
Implement Ridge regression a.k.a L2 Regularization

### ISSUE THREAD

**Issue by Saptashrungi** [RoboticsClubIITJ/ML-DL-implementation#61]
Resources:
https://www.geeksforgeeks.org/implementation-of-ridge-regression-from-scratch-using-python/
https://machinelearningmastery.com/ridge-regression-with-python/

**Comment by bhanuexcalibur** [comment]
can i please be assigned to this?

**Comment by rohansingh9001** [comment]
@bhanuexcalibur You have been issued a different issue. You can work on that one first before working on this one.

**Comment by RATED-R-SUNDRAM** [comment]
i would like to work on the issue

**Comment by kwanit1142** [comment]
Issue's Complete, thus dissolving it.
