### ISSUE TITLE
Implementation of Bayesian optimization

### ISSUE THREAD

**Issue by Saptashrungi** [RoboticsClubIITJ/ML-DL-implementation#65]
Resources:
https://machinelearningmastery.com/what-is-bayesian-optimization/
https://towardsdatascience.com/bayesian-optimization-concept-explained-in-layman-terms-1d2bcdeaf12f

**Comment by bhanuexcalibur** [comment]
can you please assign this to me?

**Comment by rohansingh9001** [comment]
@bhanuexcalibur Sure go ahead

**Comment by vighneshanand** [comment]
can this be assigned to me?

**Comment by rsrkpatwari1234** [comment]
hey @rohansingh9001!! I want to work on this issue.Can you please assign it to me?

**Comment by harsh-ux** [comment]
@kwanit1142 I would like to work on it

**Comment by kwanit1142** [comment]
@harsh-ux , you can work accordingly then.
