### ISSUE TITLE
Necessities of Score Metrics, for evaluation of ML Classifier Models

### ISSUE THREAD

**Issue by kwanit1142** [RoboticsClubIITJ/ML-DL-implementation#67]
Reference Literatures for this issue are as follows : -

https://towardsdatascience.com/metrics-to-evaluate-your-machine-learning-algorithm-f10ba6e38234

https://towardsdatascience.com/20-popular-machine-learning-metrics-part-1-classification-regression-evaluation-metrics-1ca3e282a2ce                        <---------------------(Refer this first and foremost)

**Comment by Prachi0203** [comment]
I want to work on this for now I can want to add accuracy,precision,recall, auc metrics

**Comment by kwanit1142** [comment]
@Prachi0203 , apart from the work you done, there are still more to cover, that's why the Literature for respective issue is referred, so do check them and add other Score Metric components too, like F1 , F2 Scores,etc.

**Comment by RATED-R-SUNDRAM** [comment]
hey i just wanted to ask that all these necessities have to be included in models.py ? could u guide me to exact task associated with the issue.

**Comment by kwanit1142** [comment]
@RATED-R-SUNDRAM , see #76 , although pull requested, you can still get insight.

In short, you have to make a separate file, which can be used as an import by most of the models, to showcase their scores.

**Comment by Siddharth-Singh27** [comment]
I would like to work on this issue.

**Comment by kwanit1142** [comment]
Okay, @Siddharth-Singh27

**Comment by kwanit1142** [comment]
Closing the issue, as it's PR is merged.
