### ISSUE TITLE
Improve Readme 

### ISSUE THREAD

**Issue by TarunTomar122** [RoboticsClubIITJ/ML-DL-implementation#68]
We need to write and link every algorithm and function implemented in our library in the readme.
Currently, there is no way to know what functions and algorithms have been implemented, so it is very hard for newcomers to understand the repository. We want to fix that by providing links in the Readme to all the functions and algorithms that are currently implemented  :)

**Comment by GoldExplosion** [comment]
hi, i would like to take this issue :)
can you specify what you mean by write and link? 
like give it a title and link it to website or web page where the algorithm is explained?

**Comment by rohansingh9001** [comment]
@GoldExplosion I think it just means take a table of all algorithms implemented currently. You might have to go through the code in order to do so. Also before you submit a PR, make sure that you explain the changes you are going to add incase we might need a different format.

**Comment by GoldExplosion** [comment]
@rohansingh9001, ok I think I have a general idea. Thx

**Comment by GoldExplosion** [comment]
@TarunTomar122 , i did the issue and  i have created a pull request.

**Comment by Kerveyfelix** [comment]
Can I work on this?

**Comment by kwanit1142** [comment]
I would like to suggest about the table in readme section, It would be great not to put all things in single table
instead split them according to their categories they are allotted to
like separate table for activation, another table for loss function, etc.
Also, Implemented Examples should be mentioned alongside their respective models, in the Table

**Comment by TarunTomar122** [comment]
@kwanit1142  would you like to do it? or shall I give it to @Kerveyfelix

**Comment by TarunTomar122** [comment]
I think @kwanit1142  can guide @Kerveyfelix  on what to work on for this issue. You two may start now :)

**Comment by kwanit1142** [comment]
@TarunTomar122 give it to @Kerveyfelix

**Comment by kwanit1142** [comment]
Only formatting is required for splitting tables, corresponding to categories.

**Comment by TarunTomar122** [comment]
@Kerveyfelix  keep us updated on how you are going to improvise the tables

**Comment by agrawalshubham01** [comment]
@TarunTomar122 @kwanit1142, i guess it would be better to write comment at the starting of the file something like
```
'''

Contains
========
Relu,
LeakyRelu,
Softmax,
and so on
'''

# than all the imports 

__all__ = ['Relu','LeakyRelu', 'Softmax','and so on']
```

This would reduce messiness of the initial readme file and in future if required we can add wiki to the pages to this. I guess it would be hard to maintain as we are currently maintaining.

**Comment by kwanit1142** [comment]
@TarunTomar122 @rohansingh9001 Give your insights too about this.

**Comment by TarunTomar122** [comment]
@agrawalshubham01  I think you are right.. So shall we close this issue and open another one for that?

**Comment by agrawalshubham01** [comment]
@TarunTomar122 That would be much better, we currently do not have __init__.py files after this we can implement that as well.

**Comment by GoldExplosion** [comment]
> I would like to suggest about the table in readme section, It would be great not to put all things in single table
> instead split them according to their categories they are allotted to
> like separate table for activation, another table for loss function, etc.
> Also, Implemented Examples should be mentioned alongside their respective models, in the Table

i would like to give it a try

**Comment by kwanit1142** [comment]
(@GoldExplosion) Sure, just have a look on above mentioned insights and suggestions. In addition to that, You can coordinate with @Kerveyfelix too, on improvisation.

**Comment by GoldExplosion** [comment]
Ok got it
