### ISSUE TITLE
Other variants of Relu can be added in the script activation.py

### ISSUE THREAD

**Issue by parva-jain** [RoboticsClubIITJ/ML-DL-implementation#69]
I'm willing to add other variants of the Relu activation function for a wide range of applications of this package.

**Comment by rohansingh9001** [comment]
@parva-jain Sure you can work on it. Before that can you please give a brief description of what all you are going to add?

**Comment by parva-jain** [comment]
I have heard of Parametric Relu(PRelu) and Scaled ELU(SELU) functions but only able to find out their Keras implementation till now.
Also, there can be added more activation functions like a binary step function and a swish function.

**Comment by rohansingh9001** [comment]
@parva-jain sure go ahead, you can work on them. Make sure to follow PEP 8 formatting and correctness of your code.

**Comment by kwanit1142** [comment]
LGTM too.
