### ISSUE TITLE
Add issue template

### ISSUE THREAD

**Issue by Kerveyfelix** [RoboticsClubIITJ/ML-DL-implementation#77]
Can I make issue templates to enhance the workflow of the repository?

**Comment by TarunTomar122** [comment]
Yeah, sure you can. I think it would improve the experience. Keep us updated with your work here and feel free to ask any doubts.

**Comment by Kerveyfelix** [comment]
Link to my pull request for fixing this issue: https://github.com/RoboticsClubIITJ/ML-DL-implementation/pull/87
