### ISSUE TITLE
Update Algorithms implemented table in Readme

### ISSUE THREAD

**Issue by Abjcodes** [RoboticsClubIITJ/ML-DL-implementation#79]
Currently, some of the links in the algorithms table refer to a separate branch, not the master branch. So the updates will not be shown in the resultant code referred in the links. Can I fix this?

**Comment by rohansingh9001** [comment]
Definitely go ahead. It would also be great if you could rewrite some of the headings in the table. Currently, It says "Algorithms Implemented". However, activation functions like relu and sigmoid aren't activations. They could use a different heading which does not lie under the Algorithms section.

**Comment by Abjcodes** [comment]
@rohansingh9001 Sure.

**Comment by kwanit1142** [comment]
@Abjcodes 

I would like to suggest about the table in readme section, It would be great not to put all things in single table
instead split them according to their categories they are allotted to
like separate table for activation, another table for loss function, etc.
Also, Implemented Examples should be mentioned alongside their respective models, in the Table

**Comment by kwanit1142** [comment]
Thanks to @ShreyaSachan, Readme's been updated. So, closing the Issue.
