### ISSUE TITLE
Implement Naive Bayes classification

### ISSUE THREAD

**Issue by TarunTomar122** [RoboticsClubIITJ/ML-DL-implementation#8]
Related Resources to Follow :-
1. https://towardsdatascience.com/na%C3%AFve-bayes-from-scratch-using-python-only-no-fancy-frameworks-a1904b37222d
2. https://machinelearningmastery.com/naive-bayes-classifier-scratch-python/

**Comment by Saptashrungi** [comment]
I would like to work on this issue.

**Comment by TarunTomar122** [comment]
@Saptashrungi  Go ahead this issue is yours now!

**Comment by rohansingh9001** [comment]
PR #27 Solves this issue. Hence closing this issue.
