### ISSUE TITLE
Add contributing.md file

### ISSUE THREAD

**Issue by KerinPithawala** [RoboticsClubIITJ/ML-DL-implementation#84]
I think it is important to have contributing guidelines so that an open-source contributor know how to contribute properly.
Can I work on this?

**Comment by agrawalshubham01** [comment]
@Kerveyfelix , I believe that it would be great idea. I would suggest instead of typing names and email id manually we could write a python script that could read from git, the users which have contributed i.e using mailmap and gitpython.

**Comment by Kerveyfelix** [comment]
That's a great idea, I will see if I can build a python script for the same.

**Comment by tusharnankani** [comment]
We could use the [all-contributors bot](https://allcontributors.org/docs/en/bot/overview) to do the same.
