### ISSUE TITLE
Adding Tests for the repo

### ISSUE THREAD

**Issue by agrawalshubham01** [RoboticsClubIITJ/ML-DL-implementation#85]
Currently we are missing important part of the repo i.e the **tests**. I believe this couldn't be done in 1 PR. So multiple small PRs could be made. This could be tested by **pytest**. Then this could be merged with travis-ci.

**Comment by parva-jain** [comment]
Can you tell what exactly the test scripts should contain and also one script for one function test or multiple functions?

**Comment by parva-jain** [comment]
As per my understanding, I can make a test folder inside MLib and then a loss folder inside the test folder and then different test scripts for all loss functions, right?

**Comment by agrawalshubham01** [comment]
@parva-jain I guess I will first initialise test and write an example, so that there would be no confusion. The basic structure would be like for activation.py we can create a file in `MLlib/Tests` named `test_activation.py`. Each subfolder could have another sub folder inside it named Tests where tests can be added.

**Comment by parva-jain** [comment]
Alright...looking forward to contributing to it.

**Comment by agrawalshubham01** [comment]
@parva-jain i have made pr for initialising pytest, after getting merge you could see that I have made a folder tests in which `test_activations.py` is there, we will mantain same hierarchy.

**Comment by parva-jain** [comment]
Alright.

**Comment by kwanit1142** [comment]
Thanks to @hiteshidudeja , for adding the remaining Test modules for activation Functions. Closing this Finished Issue.
