### ISSUE TITLE
Add Linear_Regression_using_PyTorch

### ISSUE THREAD

**Issue by Halix267** [RoboticsClubIITJ/ML-DL-implementation#90]
Can i work on this @agrawalshubham01

**Comment by kwanit1142** [comment]
You can refer the Readme.md File for information related to constrained usage of libraries, but Our implementations are only based upon Numpy and Matplotlib. So, I dont think PyTorch should be used, else you can still ask @agrawalshubham01 .

**Comment by Halix267** [comment]
@kwanit1142 can u check my other issues also is that issues are rlevant

**Comment by agrawalshubham01** [comment]
@kwanit1142 agreed, also was thinking to export this to pytorch but turns out pytorch has already a feature called  [torch.from_numpy](https://pytorch.org/docs/stable/generated/torch.from_numpy.html). So this as well doesn't make sense as our core is on numpy.
