### ISSUE TITLE
Principal component analysis (PCA)

### ISSUE THREAD

**Issue by Halix267** [RoboticsClubIITJ/ML-DL-implementation#92]
Can I work on this @agrawalshubham01 @kwanit1142

**Comment by kwanit1142** [comment]
@Halix267 , listen, before uploading any more issues from now, make sure that it is not repeated.

For that, see the issues mentioned already in this repository, in which SVM,PCA was already mentioned, their implementations are almost done.

**Comment by kwanit1142** [comment]
@Halix267 A piece of advice will be, instead of adding issues in haphazard fashion, make sure that issue is more unique than former issues in repository , and not repeated.

That's the good practice for creating unique issues .
