### ISSUE TITLE
Implement "Agglomerative Hierarchical Clustering"

### ISSUE THREAD

**Issue by kwanit1142** [RoboticsClubIITJ/ML-DL-implementation#93]
Reference Literature for Working and Specific Details : -

https://stackabuse.com/hierarchical-clustering-with-python-and-scikit-learn/

https://www.analyticsvidhya.com/blog/2019/05/beginners-guide-hierarchical-clustering/   <-----(Focus only on Agglomerative Model)

For Program Structure, refer K-Means Clustering at models.py and its utilities at Utils folder, contained in MLlib folder.

**Comment by Halix267** [comment]
@kwanit1142 Can I work on this?

**Comment by kwanit1142** [comment]
@Halix267 Do You referred Readme.md and Literature associated with this issue carefully ?

**Comment by Halix267** [comment]
Yes @kwanit1142 I have read the literature and readme.

**Comment by Halix267** [comment]
And also i have knowledge about heirarcial clustering so i think i can do this issue.

**Comment by kwanit1142** [comment]
Ok then go for it and Provide updates for the same

**Comment by Halix267** [comment]
@kwanit1142 where I have to implement this algo, On a separate file or on the specific file

**Comment by kwanit1142** [comment]
@Halix267 thats why I said, see how K-Means Clustering is implemented in repository

In short, you have to make clustering class in models.py and its associated utilities at Utils folder inside MLlib folder

Also, for showing the work of Model, make Example file , with its corresponding Dataset too

**Comment by Halix267** [comment]
Ok got it ..thanks

**Comment by hiteshidudeja** [comment]
@kwanit1142 I would like to work on this issue

**Comment by kwanit1142** [comment]
Thanks to @hiteshidudeja, finally closing this Issue :)
