### ISSUE TITLE
Implement "Divisive Hierarchical Clustering"

### ISSUE THREAD

**Issue by kwanit1142** [RoboticsClubIITJ/ML-DL-implementation#94]
One of the least implemented Models for sure. Still, reference Literature associated with it are : -

https://www.analyticsvidhya.com/blog/2019/05/beginners-guide-hierarchical-clustering/  <---- (Focus on Divisive Model and Components for each Hierarchical Clustering Model)

https://www.geeksforgeeks.org/ml-hierarchical-clustering-agglomerative-and-divisive-clustering/ <---(Focus on Insight about Divisive Model)

Hereby, Video Links are also attached for better Understanding. Even after all these, if Research Papers are required for clarity, I will post it here then .

https://youtu.be/MIWVfCcHzM4
https://youtu.be/Fm01pqWLqzU

For Program Structure, refer K-Means Clustering at models.py and its utilities at Utils folder, contained in MLlib folder.

**Comment by parva-jain** [comment]
Can we use scipy or sklearn library for implementing this algo?

**Comment by kwanit1142** [comment]
(@parva-jain) The main essence of this Repository is limited usage of libraries , specifically NumPy and MatPlotLib, so 

We cannot use other libraries like Scipy and Sklearn.

**Comment by ashwani-rathee** [comment]
@kwanit1142 @rohansingh9001 can I work on this??

**Comment by Aman-1701** [comment]
@kwanit1142  Can i work on it??

**Comment by kwanit1142** [comment]
Anyone can try this Issue. 
Don't worry. @ashwani-rathee , you can try too.

**Comment by Vinit-source** [comment]
@kwanit1142 I would like to work on this issue. Sorry for the late update.

**Comment by kwanit1142** [comment]
@Vinit-source , Sure.
