### ISSUE TITLE
Add PCA algorithm

### ISSUE THREAD

**Issue by Halix267** [RoboticsClubIITJ/ML-DL-implementation#95]
Can i work on this @agrawalshubham01

**Comment by agrawalshubham01** [comment]
I would suggest first complete one issue/PR then open other, anyway on this case we cannot do anything before PCA gets merged

**Comment by kwanit1142** [comment]
@Halix267 , this issue is already posted down below, and following is the link

https://github.com/RoboticsClubIITJ/ML-DL-implementation/issues/52

**Comment by kwanit1142** [comment]
@Halix267 you can see other issues till then.
